use_frameworks!

platform :ios, '9.0'

target 'MoyaResultValidate_Example' do
  pod 'MoyaResultValidate', :path => '../'

  target 'MoyaResultValidate_Tests' do
    inherit! :search_paths

    
  end
end
